### PR TITLE
Fix node-gyp cache conflict between node and electron

### LINKED ISSUE #249: Building for Electron 5.0.0 instead builds for Node 5.0.0
If this command is run:
```
prebuild -r electron -t 5.0.0
```
It actually builds for Node v5.0.0.  However, this command builds for Electron correctly:
```
prebuild -r electron -t 5.0.6
```
And since the former command seems to be what is run when doing `prebuild --all`, this means that `prebuild` fails for Electron v5.

### PR DESCRIPTION
**Pull request by vweevers**
Adapted from `prebuildify`. Closes #249.

### CODE REVIEW

File: gypbuild.js [hunk 1]
```diff
@@ -29,6 +31,11 @@ function runGyp (opts, target, cb) {
   }
   if (opts.debug) args.push('--debug')
 
+  // Since electron and node are reusing the versions now (fx 6.0.0) and
+  // node-gyp only uses the version to store the dev files, they have started
+  // clashing. To work around this we explicitly set devdir to tmpdir/runtime(/target)
+  args.push('--devdir=' + path.join(os.tmpdir(), 'prebuild', opts.runtime || 'node'))
```
Comment (vweevers) [inline gypbuild.js]: Hm, when running tests locally I don't see this directory being created.

Comment (vweevers) [reply gypbuild.js]: Ah. Need to modify this instead:

https://github.com/prebuild/prebuild/blob/4ac850fc87bf9baef097701f7f770dffaec548e9/gyp.js#L28
